controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    test_position_controller:
      type: forward_command_controller/ForwardCommandController

test_position_controller:
  ros__parameters:
    joints:
      - test_joint
    interface_name: position
