# Goal
float32 gripper_pose_goal
string space
string interface_type
bool realtime
---
# Result
float32 gripper_pose_result
string status_result
bool success
---
# Feedback
float32 gripper_pose_feedback
string status